### PR TITLE
Workaround Argo CD cluster deletion reconciliation bug

### LINKED ISSUE #170: Workaround Argo CD cluster deletion reconciliation bug
Argo CD bug https://github.com/argoproj/argo-cd/issues/5817 causes significant issues for the Cluster generator of the ApplicationSet controller: when a cluster is deleted from Argo CD, and that cluster had Applications associated with it, Argo CD is unable to delete the Application and the application controller enters a reconciliation loop.

This is primarily an Argo CD bug, but is easily reproducible with the ApplicationSet controller (due to us supporting automated deletion of Applications on cluster deletion), hence the need to workaround it until it is fixed in v1.8 and v2.x Argo CD versions.

### PR DESCRIPTION
**Pull request by jgwest**
This PR removes the Application finalizer if the cluster destination for that Application is detected to be is invalid (for example, the cluster was removed from Argo CD, or the cluster secret was deleted). This ensures that the Application can be deleted successfully without locking up the Argo CD instance (See the parent issue for details on Argo CD's bad behaviour).

Since the cluster destination does not exist, there are no application resources to clean up, so we are safe to remove the finalizer (but until the upstream bug is fixed in supported Argo CD versions, we need to workaround it here).

Fixes #170

### CODE REVIEW

**Comment by OmerKahani** [comment]
Do we need unit tests, or can we really on the E2E tests?

File: pkg/controllers/applicationset_controller.go [hunk 1]
```diff
@@ -520,6 +520,28 @@ func (r *ApplicationSetReconciler) deleteInCluster(ctx context.Context, applicat
...
+
+			// Only check if the finalizers need to be removed IF there are finalizers to remove
+			if len(app.Finalizers) > 0 {
+				// If the destination is invalid (for example the cluster is no longer defined), then remove
+				// the application finalizers to avoid triggering Argo CD bug #5817
+				if err := argoutil.ValidateDestination(ctx, &app.Spec.Destination, r.ArgoDB); err != nil {
+					app.Finalizers = []string{}
+
+					r.Recorder.Eventf(&applicationSet, corev1.EventTypeNormal, "Updated", "Updated Application %q finalizer before deletion", app.Name)
+					appLog.Log(log.InfoLevel, "Updating application finalizer before deletion")
```
Comment (OmerKahani) [inline pkg/controllers/applicationset_controller.go:532]:
```suggestion
					appLog.Log(log.InfoLevel, "Updating application finalizer before deletion because application has an invalid destination")
```

File: pkg/controllers/applicationset_controller.go [hunk 2]
```diff
@@ -520,6 +520,28 @@ func (r *ApplicationSetReconciler) deleteInCluster(ctx context.Context, applicat
...
 		if !exists {
+
+			// Only check if the finalizers need to be removed IF there are finalizers to remove
+			if len(app.Finalizers) > 0 {
+				// If the destination is invalid (for example the cluster is no longer defined), then remove
+				// the application finalizers to avoid triggering Argo CD bug #5817
+				if err := argoutil.ValidateDestination(ctx, &app.Spec.Destination, r.ArgoDB); err != nil {
+					app.Finalizers = []string{}
+
+					r.Recorder.Eventf(&applicationSet, corev1.EventTypeNormal, "Updated", "Updated Application %q finalizer before deletion", app.Name)
```
Comment (OmerKahani) [inline pkg/controllers/applicationset_controller.go:531]:
```suggestion
					r.Recorder.Eventf(&applicationSet, corev1.EventTypeNormal, "Updated", "Updated Application %q finalizer before deletion, because application has an invalid destination", app.Name)
```

File: pkg/controllers/applicationset_controller.go [hunk 3]
```diff
@@ -520,6 +520,28 @@ func (r *ApplicationSetReconciler) deleteInCluster(ctx context.Context, applicat
 		_, exists := m[app.Name]
 
 		if !exists {
+
+			// Only check if the finalizers need to be removed IF there are finalizers to remove
+			if len(app.Finalizers) > 0 {
```
Comment (OmerKahani) [inline pkg/controllers/applicationset_controller.go:525]: we should verify that the finalizer here is "resources-finalizer.argocd.argoproj.io" and only delete that one

**Review by OmerKahani — CHANGES_REQUESTED** [review]

File: pkg/controllers/applicationset_controller.go (hunk 1 above)
Comment (jgwest) [reply pkg/controllers/applicationset_controller.go]: Done.

File: pkg/controllers/applicationset_controller.go (hunk 2 above)
Comment (jgwest) [reply pkg/controllers/applicationset_controller.go]: Done.

File: pkg/controllers/applicationset_controller.go (hunk 3 above)
Comment (jgwest) [reply pkg/controllers/applicationset_controller.go]: Done.

**Comment by jgwest** [comment]
Thanks @OmerKahani , I've updated the PR with your requested changes, and add unit tests for the new method. If you can take a look ASAP that would be great, as I'd like to update the RC driver with this change so it can be tested. Thanks :smile: !

**Review by OmerKahani — APPROVED** [review]

**Comment by OmerKahani** [comment]
> Thanks @OmerKahani , I've updated the PR with your requested changes, and add unit tests for the new method. If you can take a look ASAP that would be great, as I'd like to update the RC driver with this change so it can be tested. Thanks 😄 !

Looks great now!

**Comment by wtam2018** [comment]
LGTM
We are going to remove the workaround when the parent bug is resolved, right?   What will remind us to do that?

**Comment by jgwest** [comment]
Thanks @wtam2018 :+1: , opened https://github.com/argoproj-labs/applicationset/issues/175 to remind us, and added it to next milestone.
